# Generated by Django 5.2.4 on 2025-07-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_extendeduser_id_extendeduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='accounts.extendeduser', verbose_name='Users this user is following.'),
        ),
    ]
