# Generated by Django 5.2.4 on 2025-07-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_extendeduser_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date and time this post was made.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.extendeduser', verbose_name='Author of this post')),
            ],
        ),
    ]
