# Generated by Django 5.2.4 on 2025-07-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('pk', models.CompositePrimaryKey('follower_id', 'followee_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='accounts.extendeduser')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='accounts.extendeduser')),
            ],
        ),
    ]
