# Generated by Django 5.2.4 on 2025-07-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='following',
        ),
    ]
