# Generated by Django 5.2.4 on 2025-07-15 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_extendeduser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='private',
            field=models.BooleanField(default=False, verbose_name='True if the user is private.'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='accounts.extendeduser'),
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('pk', models.CompositePrimaryKey('follower_id', 'followee_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_follow_request', to='accounts.extendeduser')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow_request', to='accounts.extendeduser')),
            ],
        ),
    ]
